# Usar imagen oficial de Python ligera
FROM python:3.10-slim

# Definir directorio de trabajo
WORKDIR /app

# Copiar e instalar dependencias
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el código de la aplicación
COPY app.py .

# Exponer el puerto de Flask
EXPOSE 5000

# Comando para ejecutar la API
CMD ["python", "app.py"]