- name: Validar index.html
  run: test -f frontend/index.html

- name: Validar style.css
  run: test -f frontend/css/style.css

- name: Validar script.js
  run: test -f frontend/js/script.js

- name: Validar README.md
  run: test -f README.md