name: Validacion Proyecto

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Validar index.html
        run: test -f frontend/index.html

      - name: Validar style.css
        run: test -f frontend/css/style.css

      - name: Validar script.js
        run: test -f frontend/js/script.js

      - name: Validar README.md
        run: test -f README.md